FROM debian:bullseye

RUN apt-get update && apt-get -y install git gcc make libncurses-dev libssl-dev xorg-dev libsdl1.2-dev libpulse-dev libsndfile1-dev libasound2-dev

RUN git clone https://github.com/chernandezba/zesarux.git && cd zesarux/src && ./configure --enable-memptr --enable-visualmem --enable-cpustats --enable-ssl && make clean && make -j2

WORKDIR /zesarux/src

ENTRYPOINT [ "./zesarux" ]

CMD [ "--vo" , "curses", "--ao" , "null" ]
